[tox]
envlist = py38,py39,py310,py311,py312,py313,py314,flake8
skipsdist = False

[testenv]
extras = dev
commands =
    pytest

[testenv:flake8]
extras = dev
basepython = python3
commands = flake8 converter tests
